import 'bootstrap/dist/css/bootstrap.min.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/AppSidebar";
import "./globals.css";
import NavigationMenu from "@/components/NavigationMenu";
import MenubarIndex from '@/components/menubar';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
           <AppRouterCacheProvider>
       <SidebarProvider>
      <AppSidebar />
      <main className='w-100'>
      <SidebarTrigger />
      <MenubarIndex />
      
      {/* <NavigationMenu /> */}
      {/* <div className='cust-main-menu-header'>
      <NavigationMenu />
      </div> */}
      
        {children}
      </main>
    </SidebarProvider>
    </AppRouterCacheProvider>
      </body>
    </html>
  );
}
